"""organization and account

Revision ID: a7f5bb383044
Revises: 63ee5f721c76
Create Date: 2026-07-17 01:16:13.827336

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a7f5bb383044"
down_revision: str | None = "63ee5f721c76"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organization",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("deposit_percent", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organization")),
    )
    op.create_index(op.f("ix_organization_slug"), "organization", ["slug"], unique=True)
    op.add_column("user_account", sa.Column("organization_id", sa.Uuid(), nullable=False))
    op.create_index(
        op.f("ix_user_account_organization_id"), "user_account", ["organization_id"], unique=True
    )
    op.create_foreign_key(
        op.f("fk_user_account_organization_id_organization"),
        "user_account",
        "organization",
        ["organization_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_user_account_organization_id_organization"), "user_account", type_="foreignkey"
    )
    op.drop_index(op.f("ix_user_account_organization_id"), table_name="user_account")
    op.drop_column("user_account", "organization_id")
    op.drop_index(op.f("ix_organization_slug"), table_name="organization")
    op.drop_table("organization")
    # ### end Alembic commands ###
