"""tenant scoping

Revision ID: 048117bb469f
Revises: a7f5bb383044
Create Date: 2026-07-17 01:54:23.066179

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "048117bb469f"
down_revision: str | None = "a7f5bb383044"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("import_forms", sa.Column("organization_id", sa.Uuid(), nullable=False))
    op.create_index(
        op.f("ix_import_forms_organization_id"), "import_forms", ["organization_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_import_forms_organization_id_organization"),
        "import_forms",
        "organization",
        ["organization_id"],
        ["id"],
    )
    op.add_column("intake_submissions", sa.Column("organization_id", sa.Uuid(), nullable=False))
    op.create_index(
        op.f("ix_intake_submissions_organization_id"),
        "intake_submissions",
        ["organization_id"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_intake_submissions_organization_id_organization"),
        "intake_submissions",
        "organization",
        ["organization_id"],
        ["id"],
    )
    op.add_column("inventory_items", sa.Column("organization_id", sa.Uuid(), nullable=False))
    op.drop_index(op.f("ix_inventory_items_category"), table_name="inventory_items")
    op.drop_index(op.f("ix_inventory_items_sku"), table_name="inventory_items")
    op.create_index(
        op.f("ix_inventory_items_organization_id"),
        "inventory_items",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_inventory_items_organization_id_category",
        "inventory_items",
        ["organization_id", "category"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_inventory_items_organization_id_sku", "inventory_items", ["organization_id", "sku"]
    )
    op.create_foreign_key(
        op.f("fk_inventory_items_organization_id_organization"),
        "inventory_items",
        "organization",
        ["organization_id"],
        ["id"],
    )
    op.add_column("lens_coatings", sa.Column("organization_id", sa.Uuid(), nullable=False))
    op.create_index(
        op.f("ix_lens_coatings_organization_id"), "lens_coatings", ["organization_id"], unique=False
    )
    op.create_unique_constraint(
        "uq_lens_coatings_organization_id_name_en", "lens_coatings", ["organization_id", "name_en"]
    )
    op.create_foreign_key(
        op.f("fk_lens_coatings_organization_id_organization"),
        "lens_coatings",
        "organization",
        ["organization_id"],
        ["id"],
    )
    op.add_column("lens_configs", sa.Column("organization_id", sa.Uuid(), nullable=False))
    op.create_index(
        op.f("ix_lens_configs_organization_id"), "lens_configs", ["organization_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_lens_configs_organization_id_organization"),
        "lens_configs",
        "organization",
        ["organization_id"],
        ["id"],
    )
    op.add_column("lens_materials", sa.Column("organization_id", sa.Uuid(), nullable=False))
    op.create_index(
        op.f("ix_lens_materials_organization_id"),
        "lens_materials",
        ["organization_id"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_lens_materials_organization_id_name_en",
        "lens_materials",
        ["organization_id", "name_en"],
    )
    op.create_foreign_key(
        op.f("fk_lens_materials_organization_id_organization"),
        "lens_materials",
        "organization",
        ["organization_id"],
        ["id"],
    )
    op.add_column("lens_tints", sa.Column("organization_id", sa.Uuid(), nullable=False))
    op.create_index(
        op.f("ix_lens_tints_organization_id"), "lens_tints", ["organization_id"], unique=False
    )
    op.create_unique_constraint(
        "uq_lens_tints_organization_id_name_en", "lens_tints", ["organization_id", "name_en"]
    )
    op.create_foreign_key(
        op.f("fk_lens_tints_organization_id_organization"),
        "lens_tints",
        "organization",
        ["organization_id"],
        ["id"],
    )
    op.add_column("lens_types", sa.Column("organization_id", sa.Uuid(), nullable=False))
    op.create_index(
        op.f("ix_lens_types_organization_id"), "lens_types", ["organization_id"], unique=False
    )
    op.create_unique_constraint(
        "uq_lens_types_organization_id_name_en", "lens_types", ["organization_id", "name_en"]
    )
    op.create_foreign_key(
        op.f("fk_lens_types_organization_id_organization"),
        "lens_types",
        "organization",
        ["organization_id"],
        ["id"],
    )
    op.add_column("order_items", sa.Column("organization_id", sa.Uuid(), nullable=False))
    op.create_index(
        op.f("ix_order_items_organization_id"), "order_items", ["organization_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_order_items_organization_id_organization"),
        "order_items",
        "organization",
        ["organization_id"],
        ["id"],
    )
    op.add_column("orders", sa.Column("organization_id", sa.Uuid(), nullable=False))
    op.create_index(op.f("ix_orders_organization_id"), "orders", ["organization_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_orders_organization_id_organization"),
        "orders",
        "organization",
        ["organization_id"],
        ["id"],
    )
    op.add_column("patient_notes", sa.Column("organization_id", sa.Uuid(), nullable=False))
    op.create_index(
        op.f("ix_patient_notes_organization_id"), "patient_notes", ["organization_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_patient_notes_organization_id_organization"),
        "patient_notes",
        "organization",
        ["organization_id"],
        ["id"],
    )
    op.add_column("patients", sa.Column("organization_id", sa.Uuid(), nullable=False))
    op.drop_index(op.f("ix_patients_status"), table_name="patients")
    op.create_index(
        op.f("ix_patients_organization_id"), "patients", ["organization_id"], unique=False
    )
    op.create_index(
        "ix_patients_organization_id_status",
        "patients",
        ["organization_id", "status"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_patients_organization_id_rx_number", "patients", ["organization_id", "rx_number"]
    )
    op.create_foreign_key(
        op.f("fk_patients_organization_id_organization"),
        "patients",
        "organization",
        ["organization_id"],
        ["id"],
    )
    op.add_column("tips", sa.Column("organization_id", sa.Uuid(), nullable=False))
    op.drop_index(op.f("ix_tips_category"), table_name="tips")
    op.create_index(op.f("ix_tips_organization_id"), "tips", ["organization_id"], unique=False)
    op.create_index(
        "ix_tips_organization_id_category", "tips", ["organization_id", "category"], unique=False
    )
    op.create_unique_constraint(
        "uq_tips_organization_id_title_en", "tips", ["organization_id", "title_en"]
    )
    op.create_foreign_key(
        op.f("fk_tips_organization_id_organization"),
        "tips",
        "organization",
        ["organization_id"],
        ["id"],
    )
    op.add_column("visit_history", sa.Column("organization_id", sa.Uuid(), nullable=False))
    op.create_index(
        op.f("ix_visit_history_organization_id"), "visit_history", ["organization_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_visit_history_organization_id_organization"),
        "visit_history",
        "organization",
        ["organization_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_visit_history_organization_id_organization"), "visit_history", type_="foreignkey"
    )
    op.drop_index(op.f("ix_visit_history_organization_id"), table_name="visit_history")
    op.drop_column("visit_history", "organization_id")
    op.drop_constraint(op.f("fk_tips_organization_id_organization"), "tips", type_="foreignkey")
    op.drop_constraint("uq_tips_organization_id_title_en", "tips", type_="unique")
    op.drop_index("ix_tips_organization_id_category", table_name="tips")
    op.drop_index(op.f("ix_tips_organization_id"), table_name="tips")
    op.create_index(op.f("ix_tips_category"), "tips", ["category"], unique=False)
    op.drop_column("tips", "organization_id")
    op.drop_constraint(
        op.f("fk_patients_organization_id_organization"), "patients", type_="foreignkey"
    )
    op.drop_constraint("uq_patients_organization_id_rx_number", "patients", type_="unique")
    op.drop_index("ix_patients_organization_id_status", table_name="patients")
    op.drop_index(op.f("ix_patients_organization_id"), table_name="patients")
    op.create_index(op.f("ix_patients_status"), "patients", ["status"], unique=False)
    op.drop_column("patients", "organization_id")
    op.drop_constraint(
        op.f("fk_patient_notes_organization_id_organization"), "patient_notes", type_="foreignkey"
    )
    op.drop_index(op.f("ix_patient_notes_organization_id"), table_name="patient_notes")
    op.drop_column("patient_notes", "organization_id")
    op.drop_constraint(op.f("fk_orders_organization_id_organization"), "orders", type_="foreignkey")
    op.drop_index(op.f("ix_orders_organization_id"), table_name="orders")
    op.drop_column("orders", "organization_id")
    op.drop_constraint(
        op.f("fk_order_items_organization_id_organization"), "order_items", type_="foreignkey"
    )
    op.drop_index(op.f("ix_order_items_organization_id"), table_name="order_items")
    op.drop_column("order_items", "organization_id")
    op.drop_constraint(
        op.f("fk_lens_types_organization_id_organization"), "lens_types", type_="foreignkey"
    )
    op.drop_constraint("uq_lens_types_organization_id_name_en", "lens_types", type_="unique")
    op.drop_index(op.f("ix_lens_types_organization_id"), table_name="lens_types")
    op.drop_column("lens_types", "organization_id")
    op.drop_constraint(
        op.f("fk_lens_tints_organization_id_organization"), "lens_tints", type_="foreignkey"
    )
    op.drop_constraint("uq_lens_tints_organization_id_name_en", "lens_tints", type_="unique")
    op.drop_index(op.f("ix_lens_tints_organization_id"), table_name="lens_tints")
    op.drop_column("lens_tints", "organization_id")
    op.drop_constraint(
        op.f("fk_lens_materials_organization_id_organization"), "lens_materials", type_="foreignkey"
    )
    op.drop_constraint(
        "uq_lens_materials_organization_id_name_en", "lens_materials", type_="unique"
    )
    op.drop_index(op.f("ix_lens_materials_organization_id"), table_name="lens_materials")
    op.drop_column("lens_materials", "organization_id")
    op.drop_constraint(
        op.f("fk_lens_configs_organization_id_organization"), "lens_configs", type_="foreignkey"
    )
    op.drop_index(op.f("ix_lens_configs_organization_id"), table_name="lens_configs")
    op.drop_column("lens_configs", "organization_id")
    op.drop_constraint(
        op.f("fk_lens_coatings_organization_id_organization"), "lens_coatings", type_="foreignkey"
    )
    op.drop_constraint("uq_lens_coatings_organization_id_name_en", "lens_coatings", type_="unique")
    op.drop_index(op.f("ix_lens_coatings_organization_id"), table_name="lens_coatings")
    op.drop_column("lens_coatings", "organization_id")
    op.drop_constraint(
        op.f("fk_inventory_items_organization_id_organization"),
        "inventory_items",
        type_="foreignkey",
    )
    op.drop_constraint("uq_inventory_items_organization_id_sku", "inventory_items", type_="unique")
    op.drop_index("ix_inventory_items_organization_id_category", table_name="inventory_items")
    op.drop_index(op.f("ix_inventory_items_organization_id"), table_name="inventory_items")
    op.create_index(op.f("ix_inventory_items_sku"), "inventory_items", ["sku"], unique=True)
    op.create_index(
        op.f("ix_inventory_items_category"), "inventory_items", ["category"], unique=False
    )
    op.drop_column("inventory_items", "organization_id")
    op.drop_constraint(
        op.f("fk_intake_submissions_organization_id_organization"),
        "intake_submissions",
        type_="foreignkey",
    )
    op.drop_index(op.f("ix_intake_submissions_organization_id"), table_name="intake_submissions")
    op.drop_column("intake_submissions", "organization_id")
    op.drop_constraint(
        op.f("fk_import_forms_organization_id_organization"), "import_forms", type_="foreignkey"
    )
    op.drop_index(op.f("ix_import_forms_organization_id"), table_name="import_forms")
    op.drop_column("import_forms", "organization_id")
    # ### end Alembic commands ###
