"""audit fields

Revision ID: 85042019be58
Revises: 048117bb469f
Create Date: 2026-07-17 02:27:30.398313

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "85042019be58"
down_revision: str | None = "048117bb469f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("import_forms", sa.Column("created_by", sa.Uuid(), nullable=True))
    op.add_column("import_forms", sa.Column("updated_by", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_import_forms_updated_by_user_account"),
        "import_forms",
        "user_account",
        ["updated_by"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_import_forms_created_by_user_account"),
        "import_forms",
        "user_account",
        ["created_by"],
        ["id"],
    )
    op.add_column("intake_submissions", sa.Column("created_by", sa.Uuid(), nullable=True))
    op.add_column("intake_submissions", sa.Column("updated_by", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_intake_submissions_created_by_user_account"),
        "intake_submissions",
        "user_account",
        ["created_by"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_intake_submissions_updated_by_user_account"),
        "intake_submissions",
        "user_account",
        ["updated_by"],
        ["id"],
    )
    op.add_column("inventory_items", sa.Column("created_by", sa.Uuid(), nullable=True))
    op.add_column("inventory_items", sa.Column("updated_by", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_inventory_items_updated_by_user_account"),
        "inventory_items",
        "user_account",
        ["updated_by"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_inventory_items_created_by_user_account"),
        "inventory_items",
        "user_account",
        ["created_by"],
        ["id"],
    )
    op.add_column("lens_coatings", sa.Column("created_by", sa.Uuid(), nullable=True))
    op.add_column("lens_coatings", sa.Column("updated_by", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_lens_coatings_created_by_user_account"),
        "lens_coatings",
        "user_account",
        ["created_by"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_lens_coatings_updated_by_user_account"),
        "lens_coatings",
        "user_account",
        ["updated_by"],
        ["id"],
    )
    op.add_column("lens_configs", sa.Column("created_by", sa.Uuid(), nullable=True))
    op.add_column("lens_configs", sa.Column("updated_by", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_lens_configs_updated_by_user_account"),
        "lens_configs",
        "user_account",
        ["updated_by"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_lens_configs_created_by_user_account"),
        "lens_configs",
        "user_account",
        ["created_by"],
        ["id"],
    )
    op.add_column("lens_materials", sa.Column("created_by", sa.Uuid(), nullable=True))
    op.add_column("lens_materials", sa.Column("updated_by", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_lens_materials_created_by_user_account"),
        "lens_materials",
        "user_account",
        ["created_by"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_lens_materials_updated_by_user_account"),
        "lens_materials",
        "user_account",
        ["updated_by"],
        ["id"],
    )
    op.add_column("lens_tints", sa.Column("created_by", sa.Uuid(), nullable=True))
    op.add_column("lens_tints", sa.Column("updated_by", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_lens_tints_created_by_user_account"),
        "lens_tints",
        "user_account",
        ["created_by"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_lens_tints_updated_by_user_account"),
        "lens_tints",
        "user_account",
        ["updated_by"],
        ["id"],
    )
    op.add_column("lens_types", sa.Column("created_by", sa.Uuid(), nullable=True))
    op.add_column("lens_types", sa.Column("updated_by", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_lens_types_updated_by_user_account"),
        "lens_types",
        "user_account",
        ["updated_by"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_lens_types_created_by_user_account"),
        "lens_types",
        "user_account",
        ["created_by"],
        ["id"],
    )
    op.add_column(
        "order_items",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "order_items",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column("order_items", sa.Column("created_by", sa.Uuid(), nullable=True))
    op.add_column("order_items", sa.Column("updated_by", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_order_items_updated_by_user_account"),
        "order_items",
        "user_account",
        ["updated_by"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_order_items_created_by_user_account"),
        "order_items",
        "user_account",
        ["created_by"],
        ["id"],
    )
    op.add_column("orders", sa.Column("created_by", sa.Uuid(), nullable=True))
    op.add_column("orders", sa.Column("updated_by", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_orders_updated_by_user_account"), "orders", "user_account", ["updated_by"], ["id"]
    )
    op.create_foreign_key(
        op.f("fk_orders_created_by_user_account"), "orders", "user_account", ["created_by"], ["id"]
    )
    op.add_column("organization", sa.Column("created_by", sa.Uuid(), nullable=True))
    op.add_column("organization", sa.Column("updated_by", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_organization_created_by_user_account"),
        "organization",
        "user_account",
        ["created_by"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_organization_updated_by_user_account"),
        "organization",
        "user_account",
        ["updated_by"],
        ["id"],
    )
    op.add_column(
        "patient_notes",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column("patient_notes", sa.Column("created_by", sa.Uuid(), nullable=True))
    op.add_column("patient_notes", sa.Column("updated_by", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_patient_notes_updated_by_user_account"),
        "patient_notes",
        "user_account",
        ["updated_by"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_patient_notes_created_by_user_account"),
        "patient_notes",
        "user_account",
        ["created_by"],
        ["id"],
    )
    op.add_column("patients", sa.Column("created_by", sa.Uuid(), nullable=True))
    op.add_column("patients", sa.Column("updated_by", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_patients_created_by_user_account"),
        "patients",
        "user_account",
        ["created_by"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_patients_updated_by_user_account"),
        "patients",
        "user_account",
        ["updated_by"],
        ["id"],
    )
    op.add_column("tips", sa.Column("created_by", sa.Uuid(), nullable=True))
    op.add_column("tips", sa.Column("updated_by", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_tips_created_by_user_account"), "tips", "user_account", ["created_by"], ["id"]
    )
    op.create_foreign_key(
        op.f("fk_tips_updated_by_user_account"), "tips", "user_account", ["updated_by"], ["id"]
    )
    op.add_column("user_account", sa.Column("created_by", sa.Uuid(), nullable=True))
    op.add_column("user_account", sa.Column("updated_by", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_user_account_updated_by_user_account"),
        "user_account",
        "user_account",
        ["updated_by"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_user_account_created_by_user_account"),
        "user_account",
        "user_account",
        ["created_by"],
        ["id"],
    )
    op.add_column(
        "visit_history",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "visit_history",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column("visit_history", sa.Column("created_by", sa.Uuid(), nullable=True))
    op.add_column("visit_history", sa.Column("updated_by", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_visit_history_created_by_user_account"),
        "visit_history",
        "user_account",
        ["created_by"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_visit_history_updated_by_user_account"),
        "visit_history",
        "user_account",
        ["updated_by"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_visit_history_updated_by_user_account"), "visit_history", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_visit_history_created_by_user_account"), "visit_history", type_="foreignkey"
    )
    op.drop_column("visit_history", "updated_by")
    op.drop_column("visit_history", "created_by")
    op.drop_column("visit_history", "updated_at")
    op.drop_column("visit_history", "created_at")
    op.drop_constraint(
        op.f("fk_user_account_created_by_user_account"), "user_account", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_user_account_updated_by_user_account"), "user_account", type_="foreignkey"
    )
    op.drop_column("user_account", "updated_by")
    op.drop_column("user_account", "created_by")
    op.drop_constraint(op.f("fk_tips_updated_by_user_account"), "tips", type_="foreignkey")
    op.drop_constraint(op.f("fk_tips_created_by_user_account"), "tips", type_="foreignkey")
    op.drop_column("tips", "updated_by")
    op.drop_column("tips", "created_by")
    op.drop_constraint(op.f("fk_patients_updated_by_user_account"), "patients", type_="foreignkey")
    op.drop_constraint(op.f("fk_patients_created_by_user_account"), "patients", type_="foreignkey")
    op.drop_column("patients", "updated_by")
    op.drop_column("patients", "created_by")
    op.drop_constraint(
        op.f("fk_patient_notes_created_by_user_account"), "patient_notes", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_patient_notes_updated_by_user_account"), "patient_notes", type_="foreignkey"
    )
    op.drop_column("patient_notes", "updated_by")
    op.drop_column("patient_notes", "created_by")
    op.drop_column("patient_notes", "updated_at")
    op.drop_constraint(
        op.f("fk_organization_updated_by_user_account"), "organization", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_organization_created_by_user_account"), "organization", type_="foreignkey"
    )
    op.drop_column("organization", "updated_by")
    op.drop_column("organization", "created_by")
    op.drop_constraint(op.f("fk_orders_created_by_user_account"), "orders", type_="foreignkey")
    op.drop_constraint(op.f("fk_orders_updated_by_user_account"), "orders", type_="foreignkey")
    op.drop_column("orders", "updated_by")
    op.drop_column("orders", "created_by")
    op.drop_constraint(
        op.f("fk_order_items_created_by_user_account"), "order_items", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_order_items_updated_by_user_account"), "order_items", type_="foreignkey"
    )
    op.drop_column("order_items", "updated_by")
    op.drop_column("order_items", "created_by")
    op.drop_column("order_items", "updated_at")
    op.drop_column("order_items", "created_at")
    op.drop_constraint(
        op.f("fk_lens_types_created_by_user_account"), "lens_types", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_lens_types_updated_by_user_account"), "lens_types", type_="foreignkey"
    )
    op.drop_column("lens_types", "updated_by")
    op.drop_column("lens_types", "created_by")
    op.drop_constraint(
        op.f("fk_lens_tints_updated_by_user_account"), "lens_tints", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_lens_tints_created_by_user_account"), "lens_tints", type_="foreignkey"
    )
    op.drop_column("lens_tints", "updated_by")
    op.drop_column("lens_tints", "created_by")
    op.drop_constraint(
        op.f("fk_lens_materials_updated_by_user_account"), "lens_materials", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_lens_materials_created_by_user_account"), "lens_materials", type_="foreignkey"
    )
    op.drop_column("lens_materials", "updated_by")
    op.drop_column("lens_materials", "created_by")
    op.drop_constraint(
        op.f("fk_lens_configs_created_by_user_account"), "lens_configs", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_lens_configs_updated_by_user_account"), "lens_configs", type_="foreignkey"
    )
    op.drop_column("lens_configs", "updated_by")
    op.drop_column("lens_configs", "created_by")
    op.drop_constraint(
        op.f("fk_lens_coatings_updated_by_user_account"), "lens_coatings", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_lens_coatings_created_by_user_account"), "lens_coatings", type_="foreignkey"
    )
    op.drop_column("lens_coatings", "updated_by")
    op.drop_column("lens_coatings", "created_by")
    op.drop_constraint(
        op.f("fk_inventory_items_created_by_user_account"), "inventory_items", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_inventory_items_updated_by_user_account"), "inventory_items", type_="foreignkey"
    )
    op.drop_column("inventory_items", "updated_by")
    op.drop_column("inventory_items", "created_by")
    op.drop_constraint(
        op.f("fk_intake_submissions_updated_by_user_account"),
        "intake_submissions",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_intake_submissions_created_by_user_account"),
        "intake_submissions",
        type_="foreignkey",
    )
    op.drop_column("intake_submissions", "updated_by")
    op.drop_column("intake_submissions", "created_by")
    op.drop_constraint(
        op.f("fk_import_forms_created_by_user_account"), "import_forms", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_import_forms_updated_by_user_account"), "import_forms", type_="foreignkey"
    )
    op.drop_column("import_forms", "updated_by")
    op.drop_column("import_forms", "created_by")
    # ### end Alembic commands ###
