from datetime import date
from decimal import Decimal

from app.db.seeds.types import (
    LensConfigSeed,
    NoteSeed,
    PatientSeed,
    VisitSeed,
)

PATIENTS: tuple[PatientSeed, ...] = (
    PatientSeed(
        name_en="Layla Haidar",
        name_ar="ليلى حيدر",
        phone="+961 70 112 233",
        town_en="Tyre",
        town_ar="صور",
        birth_year=1991,
        last_visit=date(2026, 6, 28),
        status="active",
        rx_number="card Nr. 00274",
        rx_date=date(2026, 6, 28),
        od_sph=Decimal("-2.25"),
        od_cyl=Decimal("-0.75"),
        od_axis=180,
        os_sph=Decimal("-2.50"),
        os_cyl=Decimal("-0.50"),
        os_axis=10,
        pd_dist=Decimal("62.0"),
        pd_near=Decimal("59.0"),
        diagnosis_en="Myopia with mild astigmatism; heavy screen use.",
        diagnosis_ar="قصر نظر مع استجماتيزم خفيف؛ استخدام كثيف للشاشة.",
        tags=("myopia", "astigmatism", "screen"),
        notes=(
            NoteSeed(
                en="Reports eye strain after long work days. Recommended anti-blue coating.",
                ar="تشكو من إجهاد العين بعد أيام العمل الطويلة. أُوصي بطلاء مضاد للضوء الأزرق.",
            ),
        ),
        visits=(
            VisitSeed(
                date=date(2026, 6, 28),
                title_en="Annual eye exam",
                title_ar="فحص عين سنوي",
                detail_en="Refraction stable; updated single-vision lenses ordered.",
                detail_ar="الانكسار مستقر؛ تم طلب عدسات أحادية الرؤية محدثة.",
            ),
            VisitSeed(
                date=date(2025, 6, 15),
                title_en="First visit",
                title_ar="الزيارة الأولى",
                detail_en="Baseline refraction recorded from legacy card.",
                detail_ar="تم تسجيل الانكسار الأساسي من البطاقة القديمة.",
            ),
        ),
        lens_config=LensConfigSeed(
            lens_type="Single Vision",
            material="Thin 1.60",
            coatings=("Anti-Reflective", "Anti-Blue"),
            tint="Clear",
            frame_sku="FRM-RB-WAY-BLK",
        ),
    ),
    PatientSeed(
        name_en="Kamal Fakih",
        name_ar="كمال فقيه",
        phone="+961 71 445 667",
        town_en="Nabatieh",
        town_ar="النبطية",
        birth_year=1964,
        last_visit=date(2026, 7, 6),
        status="lab",
        rx_number="card Nr. 00281",
        rx_date=date(2026, 7, 6),
        od_sph=Decimal("+1.75"),
        od_cyl=Decimal("-0.25"),
        od_axis=90,
        od_add=Decimal("2.00"),
        os_sph=Decimal("+2.00"),
        os_cyl=Decimal("0.00"),
        os_axis=90,
        os_add=Decimal("2.00"),
        pd_dist=Decimal("64.0"),
        pd_near=Decimal("61.0"),
        diagnosis_en="Presbyopia; first-time progressive wearer.",
        diagnosis_ar="طول نظر شيخوخي؛ يرتدي العدسات المتدرجة لأول مرة.",
        tags=("presbyopia", "progressive"),
        notes=(
            NoteSeed(
                en="Counseled on progressive adaptation; follow up in two weeks.",
                ar="تم إرشاده حول التأقلم مع العدسات المتدرجة؛ متابعة بعد أسبوعين.",
            ),
        ),
        visits=(
            VisitSeed(
                date=date(2026, 7, 6),
                title_en="Progressive lens order",
                title_ar="طلب عدسات متدرجة",
                detail_en="Ordered progressive 1.67 lenses; sent to lab.",
                detail_ar="تم طلب عدسات متدرجة 1.67؛ أُرسلت إلى المختبر.",
            ),
        ),
        lens_config=LensConfigSeed(
            lens_type="Progressive / Varilux",
            material="Ultra-thin 1.67",
            coatings=("Anti-Reflective", "Scratch-resistant"),
            tint="Photo Gray",
            frame_sku="FRM-PRS-RND-GLD",
        ),
    ),
    PatientSeed(
        name_en="Nour Saad",
        name_ar="نور سعد",
        phone="+961 76 998 100",
        town_en="Saida",
        town_ar="صيدا",
        birth_year=2015,
        last_visit=date(2026, 7, 2),
        status="ready",
        rx_number="card Nr. 00293",
        rx_date=date(2026, 7, 2),
        od_sph=Decimal("-1.00"),
        od_cyl=Decimal("0.00"),
        od_axis=0,
        os_sph=Decimal("-1.25"),
        os_cyl=Decimal("0.00"),
        os_axis=0,
        pd_dist=Decimal("54.0"),
        pd_near=Decimal("51.0"),
        diagnosis_en="Early childhood myopia; monitor progression.",
        diagnosis_ar="قصر نظر مبكر في الطفولة؛ مراقبة التطور.",
        tags=("child", "myopia"),
        notes=(
            NoteSeed(
                en="Advised more outdoor time to slow myopia progression.",
                ar="نُصح بقضاء وقت أطول في الخارج لإبطاء تطور قصر النظر.",
            ),
        ),
        visits=(
            VisitSeed(
                date=date(2026, 7, 2),
                title_en="Pediatric check-up",
                title_ar="فحص أطفال",
                detail_en="First glasses prescribed; ready for pickup.",
                detail_ar="تم وصف أول نظارة؛ جاهزة للاستلام.",
            ),
        ),
        lens_config=LensConfigSeed(
            lens_type="Single Vision",
            material="Standard 1.50",
            coatings=("Scratch-resistant", "UV Protection"),
            tint="Clear",
            frame_sku="FRM-EMP-RND-SLV",
        ),
    ),
    PatientSeed(
        name_en="Hassan Zein",
        name_ar="حسن زين",
        phone="+961 3 220 559",
        town_en="Beirut",
        town_ar="بيروت",
        birth_year=1972,
        last_visit=date(2026, 6, 20),
        status="active",
        rx_number="card Nr. 00268",
        rx_date=date(2026, 6, 20),
        od_sph=Decimal("+0.50"),
        od_cyl=Decimal("-1.25"),
        od_axis=175,
        od_add=Decimal("1.75"),
        os_sph=Decimal("+0.75"),
        os_cyl=Decimal("-1.00"),
        os_axis=5,
        os_add=Decimal("1.75"),
        pd_dist=Decimal("66.0"),
        pd_near=Decimal("63.0"),
        diagnosis_en="Presbyopia with astigmatism; office worker on screens all day.",
        diagnosis_ar="طول نظر شيخوخي مع استجماتيزم؛ موظف مكتبي أمام الشاشات طوال اليوم.",
        tags=("presbyopia", "astigmatism", "screen"),
        notes=(
            NoteSeed(
                en="Office/computer lenses suit his workstation distances best.",
                ar="عدسات المكتب/الكمبيوتر تناسب مسافات محطة عمله بشكل أفضل.",
            ),
        ),
        visits=(
            VisitSeed(
                date=date(2026, 6, 20),
                title_en="Lens consultation",
                title_ar="استشارة عدسات",
                detail_en="Fitted office/computer lenses for intermediate work.",
                detail_ar="تم تركيب عدسات مكتب/كمبيوتر للعمل على المسافة المتوسطة.",
            ),
        ),
        lens_config=LensConfigSeed(
            lens_type="Office / Computer",
            material="Thin 1.60",
            coatings=("Anti-Reflective", "Anti-Blue", "UV Protection"),
            tint="Clear",
            frame_sku="FRM-GUC-RCT-BLK",
        ),
    ),
)
